### ISSUE TITLE
Code folding by file

### ISSUE THREAD

**Issue by singalen** [ThomasR/intellij-diff-plugin#3]
A patch file can be quite huge. To concentrate on a relevant diff, it would be beneficial to use code folding to reduce the space taken by the irrelevant files in the diff.

**Comment by ThomasR** [comment]
Thanks for the suggestion, but I'm not sure I understand exactly what you mean.
It should be possible to fold a whole file as well as hunks within that file

![folding](https://user-images.githubusercontent.com/136820/58685782-1fd95c00-837d-11e9-8088-14e65fdf08db.png)

Is that not working for you, or are you talking about introducing one more folding level?

**Comment by singalen** [comment]
Hm. When I filed the bug, I was under the impression that the collapse marks were not there, but now they are.
Sorry for false alarm.
