### ISSUE TITLE
Compatible with PhpStorm 2017.2 / how to install?

### ISSUE THREAD

**Issue by charginghawk** [ThomasR/intellij-diff-plugin#4]
Pretty much the title. Trying to install this with PhpStorm 2017.2, but "Install plugin from disk..." returns "Error: Plugin 'Diff / Patch File Support' is incompatible with this installation".

**Comment by ThomasR** [comment]
Thanks for the bug report!

Please understand that this is something that I won‘t fix, because the plugin uses APIs that are not available in older IntelliJ/*Storm versions.
