### ISSUE TITLE
Plugin is incompatible with 2019.2

### ISSUE THREAD

**Issue by aryehb** [ThomasR/intellij-diff-plugin#5]
![image](https://user-images.githubusercontent.com/49538279/61913446-2b737a00-af0b-11e9-93d3-c5e107b9c5a1.png)

**Comment by gease** [comment]
+1
Seems to be an indispensable plugin, but not working with current PhpStorm version (2019.2).

**Comment by ThomasR** [comment]
So far I've had no time to properly look into this. I tried to quickly update the compatibility today, but I get various errors in the build phase, which may be related to [recent changes](https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2019.html#section-1) in the Plugin API.
(Edit: and to [this](https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/#post-235))

If anyone wants to help, PRs are more than welcome.

**Comment by ThomasR** [comment]
I managed to update the compatibility, you can download a beta version here https://github.com/ThomasR/intellij-diff-plugin/releases/tag/2.1.2-SNAPSHOT

Note that this version is [buggy](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360005563519-IconLoader-returning-nothing-but-black-pixel-in-2019-2).

**Comment by ThomasR** [comment]
Fixed with [version 2.1.2](https://github.com/ThomasR/intellij-diff-plugin/releases/tag/2.1.2)
