### ISSUE TITLE
Plugin is incompatible with 2020.1

### ISSUE THREAD

**Issue by DorkmasterFlek** [ThomasR/intellij-diff-plugin#7]
Latest update to PyCharm (and presumably other) 2020.1 IDE says this plugin is not compatible.  This seems to be a simple version numbering issue.

**Comment by ThomasR** [comment]
Thank you for reporting! Fixed with [version 2.1.4](https://github.com/ThomasR/intellij-diff-plugin/releases/tag/2.1.4).
